export const config = {
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET,
  JWT_SECRET: process.env.NEXT_PUBLIC_JWT_SECRET,
  MONGODB_URI: process.env.NEXT_PUBLIC_MONGODB_URI,
  MONGODB_DB: process.env.NEXT_PUBLIC_MONGODB_DB,
  BASE_URI: process.env.NEXT_PUBLIC_BASE_URI,
  CLOUDINARY_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_NAME,
  CLOUDINARY_API_KEY: process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET,
};
