export const config = {
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET,
  MONGODB_URI: process.env.NEXT_PUBLIC_MONGODB_URI,
  MONGODB_DB: process.env.NEXT_PUBLIC_MONGODB_DB,
  BASE_URI: process.env.NEXT_PUBLIC_BASE_URI,
};
